In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [5]:
det_idx = np.array([
    [0,1,2],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])

In [ ]:
t =  np.array([
    [0,1,2],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])

In [12]:
N=5192
ifos = ["H1", "L1", "V1"]
nifos = len(ifos)
snr_dom_dict = {ifo: chisquare(4,N) + 1j*chisquare(4,N) for ifo in ifos}
snr_sub_perp_dict = {ifo: chisquare(4,N) + 1j*chisquare(4,N) for ifo in ifos}
snr_dom = np.array([snr_dom_dict[ifo] for ifo in ifos])
snr_sub_perp = np.array([snr_sub_perp_dict[ifo] for ifo in ifos])
snr_dom_above_thresh = np.array([snr_dom[i][det_idx[:,i]] for i in range(nifos)])
snr_sub_perp_above_thresh = np.array([snr_sub_perp[i][det_idx[:,i]] for i in range(nifos)])
snr_dom_above_thresh

array([[1.26391234+1.18844423j, 1.13126178+2.68680165j,
        2.62333838+1.96134688j, 2.28199361+3.94951034j],
       [0.76978806+1.47135407j, 8.48817675+6.50127033j,
        0.44959295+3.72023667j, 3.69379885+4.16718094j],
       [5.28334687+2.28200252j, 1.47819762+2.89300346j,
        2.53144986+1.85014238j, 0.58307238+5.10563151j]])

In [ ]:
snr_dom = np.array([snr_dom_dict[ifo] for ifo in ifos])
snr_sub_perp = np.array([snr_sub_perp_dict[ifo] for ifo in ifos])
snr_dom_above_thresh = np.array([snr_dom[i][det_idx[:,i]] for i in range(nifos)])
snr_sub_perp_above_thresh = np.array([snr_sub_perp[i][det_idx[:,i]] for i in range(nifos)])

In [42]:
def maximal_coinc_in_ifo(snrs, det_idx, ifo_i=0):
    """Choose the maximum network snr for each time point in ifo_i 
    (defaults to the zeroth detector)."""
    i_max = []
    j_start, j_end = 0, 0
    for c in np.unique(det_idx[:,0], return_counts=True)[1]:
        j_end += c
        i_max.append(np.argmax(snrs[j_start:j_end]) + j_start )
        j_start += c
    i_max = np.array(i_max)
    return snrs[i_max], det_idx[i_max]

In [ ]:
unique_indices : ndarray, optional
    The indices of the first occurrences of the unique values in the
    original array. Only provided if `return_index` is True.

In [39]:
np.unique(det_idx[:,0], return_index=True)[1]

array([0, 1, 2, 3])

In [36]:
for a, b in zip(np.unique(det_idx[:,0], return_counts=True)):
    print(a,b)

ValueError: not enough values to unpack (expected 2, got 1)

In [43]:
maximal_coinc_in_ifo(snr_2_filter, det_idx)

(array([12.29708041, 13.7648789 , 11.13748669, 13.37260405]),
 array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [28]:
shape(snr_2_filter), shape(det_idx)

((4,), (4, 3))

In [ ]:
maximal_coinc_in_ifo()

In [19]:
argmax(snr_dom)+1

5637

In [15]:
def snr_2_filter_stat(snr_dom, snr_sub_perp):
    network_rho_dom = np.linalg.norm(snr_dom, axis=0)
    def inner_complex(a, b):
        """Assumes a 2D array of detector SNRs where zeroth index selects a detector."""
        return abs(np.sum(a * b.conjugate(), axis=0))
    network_rho_sub_perp = inner_complex(snr_dom, snr_sub_perp) / network_rho_dom
    snr_2_filter = np.sqrt(network_rho_sub_perp**2 + network_rho_dom**2)
    return snr_2_filter, network_rho_dom, network_rho_sub_perp

In [26]:
snr_2_filter, _, _ = snr_2_filter_stat(snr_dom_above_thresh, snr_sub_perp_above_thresh)

In [197]:
_ii = -2
abs(inner(snr_dom[:,_ii], snr_sub.conjugate()[:,_ii])) / np.linalg.norm(snr_dom[:,_ii])

7.576102584943136

In [202]:
t =  np.array([
    [0,1,2],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])
snr_dom_above_thresh = [snr_dom[i][t[:,i]] for i in range(nifos)]

[array([4.78038727+2.99488504j, 1.69305592+2.17791052j,
        3.64015612+1.66458762j, 7.69046878+7.76128523j]),
 array([2.64896016+1.29668189j, 3.6181823 +2.22832394j,
        4.93845176+3.26707386j, 2.96296655+2.30445226j]),
 array([0.91243071+4.92817031j, 3.61764241+2.64964261j,
        8.01324257+2.90713367j, 5.08302249+4.54900895j])]

In [215]:
snr_dom[2][6]

(3.617642410987245+2.6496426096218477j)

In [74]:
t1, t2 = t_i.T

In [77]:
t1

array([[0, 1],
       [3, 2],
       [1, 2]])

In [78]:
t[t1, t2], t[t1, t2].sum(0)

(array([[ 0,  4],
        [11,  8],
        [ 6,  9]]),
 array([17, 21]))

In [62]:
t1

array([0, 3, 1])

In [73]:
t_i = np.array([
    [[0, 0], [3, 1], [1, 2]],
   [[1, 0], [2, 1], [2, 2]]
]
)
# np.take(t, t_i, 0)
# t[t_i]
t_i

array([[[0, 0],
        [3, 1],
        [1, 2]],

       [[1, 0],
        [2, 1],
        [2, 2]]])

In [ ]:
np.take()

In [85]:
snr_dom

array([[ 3.87647626 +5.44111556j,  2.9640498  +4.24305498j,
         3.10402073 +2.4400725j , ...,  3.21861819 +7.37129969j,
         7.51580682 +0.92449777j,  4.53872952 +1.77752759j],
       [ 3.23399167 +1.49873445j,  4.1414626  +2.40431431j,
         2.11554668 +4.3687611j , ...,  3.75215153 +2.60930988j,
         4.32648329 +0.92192494j, 10.63410997 +1.52426001j],
       [ 2.09528795 +2.11729077j, 17.8491808 +11.36794703j,
         1.37261023 +3.07954792j, ...,  7.55575983 +0.96103604j,
         4.72874385+11.00896183j,  5.0624211  +2.38578445j]])

In [181]:
abs(np.sum(snr_dom * snr_sub.conjugate(), axis=0)) / np.linalg.norm(snr_dom, axis=0)

array([ 3.73326238,  5.8296146 ,  7.15149084, ...,  8.03859646,
        5.18058266, 10.56906832])

In [192]:
_ii = -2
abs(inner(snr_dom[:,_ii], snr_sub.conjugate()[:,_ii])) / np.linalg.norm(snr_dom[:,_ii])

snr_dom = np.array([snr_dom_dict[ifo] for ifo in ifos])
snr_sub = np.array([snr_sub_dict[ifo] for ifo in ifos])
snr_dom

5.180582656233999

In [175]:
abs(np.sum(snr_dom * snr_sub.conjugate(), axis=0)) / np.linalg.norm(snr_dom, axis=0)

array([ 3.73326238,  5.8296146 ,  7.15149084, ...,  8.03859646,
        5.18058266, 10.56906832])

In [171]:
abs(sum(snr_dom * snr_dom.conjugate(), axis=0)) / linalg.norm(snr_dom, axis=0), linalg.norm(snr_dom, axis=0)

(array([ 8.13700593, 22.30571724,  7.10761451, ..., 11.98314642,
        14.84818879, 13.05708269]),
 array([ 8.13700593, 22.30571724,  7.10761451, ..., 11.98314642,
        14.84818879, 13.05708269]))

In [157]:
snr_dom = np.array([snr_dom_dict[ifo] for ifo in ifos])
snr_sub = np.array([snr_sub_dict[ifo] for ifo in ifos])
snr_dom

array([[ 3.87647626 +5.44111556j,  2.9640498  +4.24305498j,
         3.10402073 +2.4400725j , ...,  3.21861819 +7.37129969j,
         7.51580682 +0.92449777j,  4.53872952 +1.77752759j],
       [ 3.23399167 +1.49873445j,  4.1414626  +2.40431431j,
         2.11554668 +4.3687611j , ...,  3.75215153 +2.60930988j,
         4.32648329 +0.92192494j, 10.63410997 +1.52426001j],
       [ 2.09528795 +2.11729077j, 17.8491808 +11.36794703j,
         1.37261023 +3.07954792j, ...,  7.55575983 +0.96103604j,
         4.72874385+11.00896183j,  5.0624211  +2.38578445j]])

In [158]:
snr_sub = np.array([snr_sub_dict[ifo] for ifo in ifos])
snr_sub

array([[0.80219685 +1.97329441j, 4.53014471+12.28651343j,
        1.44720694 +3.03920992j, ..., 0.0457142  +4.95846999j,
        1.8834586  +5.19190523j, 6.28135869 +6.48895383j],
       [1.45938869 +0.35111855j, 3.65986597 +4.28068416j,
        6.23666255 +1.4232105j , ..., 2.01298015 +4.24593038j,
        1.80799774 +6.61008515j, 1.20749383 +2.81823702j],
       [1.99501663 +3.18432017j, 1.24955237 +1.12078583j,
        4.33775334 +1.21504659j, ..., 1.2188428  +5.46179641j,
        2.75121709 +1.69087957j, 9.11741279 +7.8474128j ]])

In [134]:
abs(inner(snr_dom.T[-2], snr_sub.conjugate()[-2]))

76.92226934459337

In [152]:
abs(inner(snr_dom.T, snr_dom.T.conjugate()))

array([[ 66.21086557, 113.68635416,  48.61238282, ...,  86.49643162,
         87.28733635,  86.76783239],
       [113.68635416, 497.54502144, 108.7391596 , ..., 216.54461258,
        277.36260931, 192.32263893],
       [ 48.61238282, 108.7391596 ,  50.51818405, ...,  63.20182484,
         85.33436552,  86.96408341],
       ...,
       [ 86.49643162, 216.54461258,  63.20182484, ..., 143.59579821,
         97.6984112 , 117.95514898],
       [ 87.28733635, 277.36260931,  85.33436552, ...,  97.6984112 ,
        220.46871047, 138.81746359],
       [ 86.76783239, 192.32263893,  86.96408341, ..., 117.95514898,
        138.81746359, 170.48740828]])

In [179]:
abs(vdot(snr_dom[:,-2], snr_sub[:,-2])) / linalg.norm(snr_dom[:,-2])

5.180582656233999

In [180]:
sum(abs(snr_dom.T * snr_sub.conjugate()), axis=1) / linalg.norm(snr_dom.T, axis=-1)

ValueError: operands could not be broadcast together with shapes (5192,3) (3,5192) 

In [165]:
sum(abs(snr_dom * snr_sub.conjugate()), axis=0) / linalg.norm(snr_dom, axis=0)

array([ 3.78202747,  5.84016836,  8.37551133, ...,  8.67747721,
        7.46414134, 11.05005264])

In [155]:
snr_dom.T 

array([[ 3.87647626 +5.44111556j,  3.23399167 +1.49873445j,
         2.09528795 +2.11729077j],
       [ 2.9640498  +4.24305498j,  4.1414626  +2.40431431j,
        17.8491808 +11.36794703j],
       [ 3.10402073 +2.4400725j ,  2.11554668 +4.3687611j ,
         1.37261023 +3.07954792j],
       ...,
       [ 3.21861819 +7.37129969j,  3.75215153 +2.60930988j,
         7.55575983 +0.96103604j],
       [ 7.51580682 +0.92449777j,  4.32648329 +0.92192494j,
         4.72874385+11.00896183j],
       [ 4.53872952 +1.77752759j, 10.63410997 +1.52426001j,
         5.0624211  +2.38578445j]])

In [150]:
linalg.norm(snr_dom.T, axis=-1)

array([ 8.13700593, 22.30571724,  7.10761451, ..., 11.98314642,
       14.84818879, 13.05708269])

In [138]:
abs(vdot(snr_dom.T[-2], snr_sub[-2]))

76.92226934459337

In [144]:
abs(sum(array([1+3j, 2+8j]))), sum(abs(array([1+3j, 2+1j])))

(11.40175425099138, 5.39834563766817)

In [130]:
abs(sum(snr_dom.T * snr_sub.conjugate(), axis=1))

array([ 30.37757812, 130.03373496,  50.83004009, ...,  96.32767847,
        76.92226934, 138.00119892])

In [136]:
sum(abs(snr_dom.T * snr_sub.conjugate()), axis=1)

array([ 30.77437995, 130.26914416,  59.52990585, ..., 103.98347997,
       110.8289798 , 144.28145095])

In [103]:
abs(dot(snr_dom.T, snr_sub.conjugate().T))

array([[ 30.37757812, 112.04176925,  56.60636461, ...,  66.46937701,
         66.09166281, 103.60566294],
       [ 95.88766525, 130.03373496, 141.77571427, ..., 166.02017014,
        122.87360824, 312.16907352],
       [ 24.68433156,  77.72745478,  50.83004009, ...,  56.88407701,
         61.28107867,  87.67710436],
       ...,
       [ 46.24562873, 141.97493111,  88.38069669, ...,  96.32767847,
         96.60439257, 159.71394106],
       [ 59.43832332, 126.32065628,  78.48659463, ..., 106.48184096,
         76.92226934, 190.75974543],
       [ 45.70518866, 132.44501381, 106.07706185, ..., 105.41676541,
        110.83906694, 138.00119892]])

In [119]:
shape(abs(einsum(snr_dom.T, snr_sub.conjugate(), axes=0)))

(5192, 3, 5192, 3)

In [92]:
np.inner?

In [ ]:
net_snr_perp = abs(np.inner(snr_dom, snr_sub.conjugate())) / rss_snr_perp['22']

In [91]:
linalg.norm(snr_dom.T[0])

8.137005934290766

In [89]:
linalg.norm(snr_dom.T, axis=-1)

array([ 8.13700593, 22.30571724,  7.10761451, ..., 11.98314642,
       14.84818879, 13.05708269])

In [26]:
t =abs(np.inner(snr_dom, snr_sub.conjugate()))

In [30]:
shape(t), shape(snr_sub)

((5192, 5192), (5192, 3))

In [38]:
inner([1,2,3], [2, 4, 6]) / linalg.norm([1,2,3])

7.483314773547883

In [40]:
linalg.norm([2, 4, 6])

7.483314773547883

In [35]:
inner([[1,2,3], [2,3,4]], [[5,6,7], [8,9,1]])

array([[38, 29],
       [56, 47]])

In [23]:
rss_snr_dom = linalg.norm(abs(snr_dom), axis=-1)

In [25]:
len(rss_snr_dom)

5192

In [ ]:
net_snr_perp = abs(np.inner(snr_dom, snr_sub.conjugate())) / rss_snr_perp['22']