In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
from numba import njit

In [943]:
a = 1+3j
b = 1.3 - 20j
real(sqrt(a * a.conjugate() + b * b.conjugate())), sqrt(real(a * a.conjugate() + b * b.conjugate()))

(20.290145391297717, 20.290145391297717)

In [940]:
a * a.conjugate() + b * b.conjugate()

(411.69+0j)

In [ ]:
(a**2 + b**2)**0.5

In [945]:
abs(b)**2

401.69000000000005

In [118]:
import pycbc.psd

In [ ]:
pycbc.psd.aLIGOAdVO3LowT1800545

In [119]:
radians(60)

1.0471975511965976

In [120]:
from pycbc.detector import Detector

In [121]:
ifo = Detector("H1")

In [124]:
(ifo.optimal_orientation(1187008882))

(0.6449118650316379, 0.810795263791696)

In [130]:
@njit
def three_det_sum_jit(t1, t2, t3, t2_coinc_window, t3_coinc_window):
    N = len(t1)
    temp = array([
        t1[i] + t2[j] + t3[k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return temp

In [129]:
for i in range(1,1):
    print(i)

In [816]:
sum((t1+t2+t3)>7**2) / len(t1)

0.03765106201171875

In [818]:
int(0.04*n_c)

3952994

In [891]:
%load_ext Cython

In [908]:
%%cython

import numpy as np
cimport numpy as cnp
from cython import wraparound, boundscheck, cdivision
from libc.math cimport M_PI, sqrt


ctypedef fused REALTYPE:
    float
    double
    
# @boundscheck(False)
# @wraparound(False)
# @cdivision(True)
# def findchirp_cluster_over_window_cython\
#         (cnp.ndarray[cnp.int32_t, ndim=1] times,
#          cnp.ndarray[REALTYPE, ndim=1] absvalues, int window_length,
#          cnp.ndarray[cnp.int32_t, ndim=1] indices, int tlen):
#     cdef int j = 0
#     cdef int curr_ind = 0
#     cdef int i
    
#     for i in range(tlen):
#         if ((times[i] - times[curr_ind]) > window_length):
#             j += 1
#             indices[j] = i
#             curr_ind = i
#         elif (absvalues[i] > absvalues[curr_ind]):
#             indices[j] = i
#             curr_ind = i
#     return j

@boundscheck(False)
@wraparound(False)
@cdivision(True)
def three_det_sum_idx_cython(
    cnp.ndarray[REALTYPE, ndim=1] t1,
    cnp.ndarray[REALTYPE, ndim=1] t2,
    cnp.ndarray[REALTYPE, ndim=1] t3,
    cnp.ndarray[REALTYPE, ndim=1] rho_net_sq,
    cnp.ndarray[long, ndim=1] idx_1,
    cnp.ndarray[long, ndim=1] idx_2,
    cnp.ndarray[long, ndim=1] idx_3):
    rho_net_sq = t1[idx_1] + t2[idx_2] + t3[idx_3]
    return 1

@boundscheck(False)
@wraparound(False)
@cdivision(True)
def three_det_sum_cython(
    cnp.ndarray[REALTYPE, ndim=1] t1,
    cnp.ndarray[REALTYPE, ndim=1] t2,
    cnp.ndarray[REALTYPE, ndim=1] t3,
    cnp.ndarray[REALTYPE, ndim=1] rho_net_sq,
    int t2_coinc_window,
    int t3_coinc_window,
    int tlen):

    cdef int m = 0
    
    for i in range(tlen):
        for j in range(max(i-t2_coinc_window, 0), min(tlen, i+t2_coinc_window+1)):
            for k in range(max(i-t3_coinc_window, 0), min(tlen, i+t3_coinc_window+1)):
                m += 1
                rho_net_sq[m] = t1[i] + t2[j] + t3[k]
    return m


In file included from /Users/camill/.ipython/cython/_cython_magic_79d94a69e0614dc2d86fcc3702c664d6.c:725:
In file included from /Users/camill/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/camill/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/camill/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
/Users/camill/miniconda3/envs/igwn-py38/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
/Users/camill/.ipython/cython/_cython_magic_79d94a69e0614dc2d86fcc3702c664d6.c:19799:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
  0, /*tp_print*/
  ^
/Us

In [911]:
_temp_cython = np.zeros(98824858)

In [904]:
%time three_det_sum_cython(t1, t2, t3, _temp_cython, t2_coinc_window, t3_coinc_window, len(t1))

CPU times: user 54.3 s, sys: 836 ms, total: 55.1 s
Wall time: 54.9 s


98824858

In [912]:
%time three_det_sum_idx_cython(t1, t2, t3, _temp_cython, idx_1, idx_2, idx_3)

CPU times: user 754 ms, sys: 988 ms, total: 1.74 s
Wall time: 1.74 s


1

In [ ]:
three_det_sum_idx_array_jit()

In [918]:
%time temp = three_det_sum_idx_array_jit(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 530 ms, sys: 889 ms, total: 1.42 s
Wall time: 1.41 s


In [917]:
%time temp = three_det_sum_idx_array(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 629 ms, sys: 645 ms, total: 1.27 s
Wall time: 1.27 s


In [819]:
@njit
def three_det_sum_jit(t1, t2, t3, t2_coinc_window, t3_coinc_window):
    N = len(t1)
    temp = array([
        t1[i] + t2[j] + t3[k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return temp

def three_det_sum(t1, t2, t3, t2_coinc_window, t3_coinc_window):
    N = len(t1)
    temp = array([
        t1[i] + t2[j] + t3[k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return temp

@njit
def three_det_sum_idx_jit(t1, t2, t3, idx):
    temp = array([
        t1[i] + t2[j] + t3[k]
            for i,j,k in idx
                ])
    return temp

def three_det_sum_idx(t1, t2, t3, idx):
    temp = array([
        t1[i] + t2[j] + t3[k]
            for i,j,k in idx
                ])
    return temp

@njit
def three_det_sum_idx_array_jit(t1, t2, t3, idx_1, idx_2, idx_3):
    return t1[idx_1] + t2[idx_2] + t3[idx_3]

@njit
def three_det_sum_idx_array_take_jit(t1, t2, t3, idx_1, idx_2, idx_3):
    return take(t1,idx_1) + take(t2,idx_2) + take(t3,idx_3)

def three_det_sum_idx_array_take(t1, t2, t3, idx_1, idx_2, idx_3):
    return take(t1,idx_1) + take(t2,idx_2) + take(t3,idx_3)

def three_det_sum_idx_array(t1, t2, t3, idx_1, idx_2, idx_3):
#     t1 = t1[idx_1]
#     t2 = t2[idx_2]
#     t3 = t3[idx_3]
    return t1[idx_1] + t2[idx_2] + t3[idx_3]

def two_det_sum(t1, t2, t2_coinc_window):
    N = len(t1)
    temp = array([
        t1[i] + t2[j]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                ])
    return temp

In [1128]:
s = slice(10, 512)

In [1137]:
s.stop - s.start

502

In [1109]:
idx[array([0,1,-1])]

array([[     0,      0,      0],
       [     0,      0,      1],
       [262143, 262143, 262143]])

In [1111]:
s = slice(20,30)

In [1126]:
l = [slice(20,30), slice(20,30), slice(20,30), slice(20,31)]

In [1127]:
np.unique(l)

array([slice(20, 30, None), slice(20, 31, None)], dtype=object)

In [1118]:
s.start

20

In [531]:
idx_1 = idx[:,0]
idx_2 = idx[:,1]
idx_3 = idx[:,2]

In [242]:
l1 = [1,2,3]
l2 = [5,6,7]
l3 = [10,11,12]
o1, o2, o3 = meshgrid(l1, l2, l3, indexing="ij")

In [250]:
array(l1)[array([0,1,0])]

array([1, 2, 1])

In [243]:
o1.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3])

In [244]:
o2.flatten()

array([5, 5, 5, 6, 6, 6, 7, 7, 7, 5, 5, 5, 6, 6, 6, 7, 7, 7, 5, 5, 5, 6,
       6, 6, 7, 7, 7])

In [245]:
o3.flatten()

array([10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11,
       12, 10, 11, 12, 10, 11, 12, 10, 11, 12])

In [948]:
%time _idx = get_indices_jit(N, t2_coinc_window, t3_coinc_window)

CPU times: user 19.1 s, sys: 2.41 s, total: 21.5 s
Wall time: 21.4 s


In [ ]:
    n_c = number_coincident_combinations(N, t2_coinc_window, t3_coinc_window)
    n_tail = number_tail(t2_coinc_window, t3_coinc_window)
    largest_window = max(t2_coinc_window, t3_coinc_window)
    if (coinc_idx > n_tail-1)&(coinc_idx < n_c-n_tail):
        i, remainder = divmod(coinc_idx - n_tail, (2*t2_coinc_window+1)*(2*t3_coinc_window+1))
        i += largest_window + 1
        j, remainder_2 = divmod(remainder, (2*t3_coinc_window+1))
        j += i - (t2_coinc_window)
        k = remainder_2 + i - (t3_coinc_window)

In [1034]:
idx_1_ends, idx_2_ends, idx_3_ends = get_indices_jit(
        2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window).T

In [1035]:
if not (coinc_idx > (n_tail-1)):
    # at the beginning
    i, j, k = precalculated_idxs[coinc_idx]
else:
    # at the end
    i, j, k = precalculated_idxs[coinc_idx - (n_c+1)] + N - (2*t3_coinc_window + 2)

10266

In [1037]:
idx_3_ends + N - (2*t3_coinc_window + 2)

array([262110, 262111, 262112, ..., 262141, 262142, 262143])

In [ ]:
return_indices(N, t2_coinc_window, t3_coinc_window)

In [1100]:
def return_coinc_indices(N, t2_coinc_window, t3_coinc_window):
    # forgetting the tails at first
    largest_window = max(t2_coinc_window, t3_coinc_window)
    idx_1_mid = np.arange(N - 2*(t3_coinc_window+1)).repeat( \
        (2*t2_coinc_window+1)*(2*t3_coinc_window+1) \
    ) + largest_window + 1
    idx_2_mid = idx_1_mid + np.tile(
        np.arange(-t2_coinc_window, t2_coinc_window+1).repeat(2*t3_coinc_window+1), 
        (N - 2*(t3_coinc_window+1))
    )
    idx_3_mid = idx_1_mid + np.tile(
        np.arange(-t3_coinc_window, t3_coinc_window+1), 
        (N - 2*(t3_coinc_window+1)) * (2*t2_coinc_window+1)
    )
    idx_1_ends, idx_2_ends, idx_3_ends = get_indices_jit(
        2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window).T
    # now get the tails
    n_start = int(len(idx_1_ends) / 2)
    idx_1 = np.concatenate((idx_1_ends[:n_start], idx_1_mid, idx_1_ends[-n_start:] + N - (2*t3_coinc_window + 2)))
    idx_2 = np.concatenate((idx_2_ends[:n_start], idx_2_mid, idx_2_ends[-n_start:] + N - (2*t3_coinc_window + 2)))
    idx_3 = np.concatenate((idx_3_ends[:n_start], idx_3_mid, idx_3_ends[-n_start:] + N - (2*t3_coinc_window + 2)))
    return np.array([idx_1, idx_2, idx_3]).T

In [1081]:
%time idx_1_ends, idx_2_ends, idx_3_ends = get_indices_jit( \
    2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window).T
len(idx_1_ends)

CPU times: user 5.39 ms, sys: 187 µs, total: 5.58 ms
Wall time: 5.52 ms


10266

In [1103]:
%time idx_t = return_indices(N, t2_coinc_window, t3_coinc_window)

CPU times: user 1.86 s, sys: 2.81 s, total: 4.68 s
Wall time: 4.9 s


In [1102]:
idx_t

array([[     0,      0,      0],
       [     0,      0,      1],
       [     0,      0,      2],
       ...,
       [262143, 262143, 262141],
       [262143, 262143, 262142],
       [262143, 262143, 262143]])

In [1104]:
%time idx = get_indices_jit(N, t2_coinc_window, t3_coinc_window)

CPU times: user 19.9 s, sys: 5.49 s, total: 25.4 s
Wall time: 26.9 s


In [1073]:
%time idx_1_t, idx_2_t, idx_3_t = return_indices(N, t2_coinc_window, t3_coinc_window)

CPU times: user 1.52 s, sys: 2.58 s, total: 4.1 s
Wall time: 4.35 s


In [1052]:
%time idx_1, idx_2, idx_3 = get_indices_jit(N, t2_coinc_window, t3_coinc_window).T

CPU times: user 19.2 s, sys: 2.78 s, total: 22 s
Wall time: 21.9 s


In [1074]:
all(idx_1_t == idx_1)

True

In [1076]:
all(idx_2_t == idx_2)

True

In [1077]:
all(idx_3_t == idx_3)

True

In [1075]:
len(idx_1_t) - len(idx_1)

0

In [989]:
largest_window = max(t2_coinc_window, t3_coinc_window)
idx_1_mid = arange(N - 2*(t3_coinc_window+1)).repeat( \
    (2*t2_coinc_window+1)*(2*t3_coinc_window+1) \
) + largest_window + 1
idx_2_mid = idx_1_mid + tile(
    arange(-t2_coinc_window, t2_coinc_window+1).repeat(2*t3_coinc_window+1), 
    (N - 2*(t3_coinc_window+1))
)
idx_3_mid = idx_1_mid + tile(
    arange(-t3_coinc_window, t3_coinc_window+1), 
    (N - 2*(t3_coinc_window+1)) * (2*t2_coinc_window+1)
)
len(mid)

CPU times: user 615 ms, sys: 196 ms, total: 810 ms
Wall time: 805 ms


112445190

In [ ]:
idx_2_mid = idx_1_mid.copy()
idx_2_mid

In [996]:
2*t3_coinc_window+1

33

In [ ]:
tile()

In [1001]:
idx_2_mid = idx_1_mid + tile(
    arange(-t2_coinc_window, t2_coinc_window+1).repeat(2*t3_coinc_window+1), 
    (N - 2*(t3_coinc_window+1))
)
idx_3_mid = idx_1_mid + tile(
    arange(-t3_coinc_window, t3_coinc_window+1), 
    (N - 2*(t3_coinc_window+1)) * (2*t2_coinc_window+1)
)
len(idx_2_mid), idx_2_mid

(112445190, array([    11,     11,     11, ..., 262132, 262132, 262132]))

In [1016]:
idx_3_mid = idx_1_mid + tile(
    arange(-t3_coinc_window, t3_coinc_window+1), 
    (N - 2*(t3_coinc_window+1)) * (2*t2_coinc_window+1)
)
len(idx_3_mid), idx_3_mid

(112445190, array([-16, -15, -14, ...,  14,  15,  16]))

In [1005]:
arange(-t3_coinc_window, t3_coinc_window+1)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14,  15,  16])

In [992]:
idx_2, idx_1

(array([     0,      0,      0, ..., 262143, 262143, 262143]),
 array([     0,      0,      0, ..., 262143, 262143, 262143]))

In [ ]:
        i, remainder = divmod(coinc_idx - n_tail, (2*t2_coinc_window+1)*(2*t3_coinc_window+1))
        i += largest_window + 1
        j, remainder_2 = divmod(remainder, (2*t3_coinc_window+1))
        j += i - (t2_coinc_window)
        k = remainder_2 + i - (t3_coinc_window)

In [ ]:
idx_2_mid = 

In [983]:
mid

array([    17,     17,     17, ..., 262126, 262126, 262126])

In [975]:
(N - 2*(t3_coinc_window+1)) * (2*t2_coinc_window+1)*(2*t3_coinc_window+1)

112445190

In [976]:
(N - 2*(t3_coinc_window+1))

262110

In [967]:
return_indices(N, t2_coinc_window, t3_coinc_window)

112445190


(262110, 0)

In [204]:
@njit
def get_indices_jit(N, t2_coinc_window, t3_coinc_window):
    idx = array([
        [i,j,k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return idx

def get_indices(N, t2_coinc_window, t3_coinc_window):
    idx = array([
        [i,j,k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return idx

In [552]:
t2_coinc_window, t3_coinc_window, (t3_coinc_window + sum(range(14))), 7*15

(6, 14, 105, 105)

In [561]:
sum(range(14+2))

120

In [568]:
8*17

136

In [567]:
sum(range(16+1))

136

In [563]:
idx[:106]

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [ 0,  0,  2],
       [ 0,  0,  3],
       [ 0,  0,  4],
       [ 0,  0,  5],
       [ 0,  0,  6],
       [ 0,  0,  7],
       [ 0,  0,  8],
       [ 0,  0,  9],
       [ 0,  0, 10],
       [ 0,  0, 11],
       [ 0,  0, 12],
       [ 0,  0, 13],
       [ 0,  0, 14],
       [ 0,  1,  0],
       [ 0,  1,  1],
       [ 0,  1,  2],
       [ 0,  1,  3],
       [ 0,  1,  4],
       [ 0,  1,  5],
       [ 0,  1,  6],
       [ 0,  1,  7],
       [ 0,  1,  8],
       [ 0,  1,  9],
       [ 0,  1, 10],
       [ 0,  1, 11],
       [ 0,  1, 12],
       [ 0,  1, 13],
       [ 0,  1, 14],
       [ 0,  2,  0],
       [ 0,  2,  1],
       [ 0,  2,  2],
       [ 0,  2,  3],
       [ 0,  2,  4],
       [ 0,  2,  5],
       [ 0,  2,  6],
       [ 0,  2,  7],
       [ 0,  2,  8],
       [ 0,  2,  9],
       [ 0,  2, 10],
       [ 0,  2, 11],
       [ 0,  2, 12],
       [ 0,  2, 13],
       [ 0,  2, 14],
       [ 0,  3,  0],
       [ 0,  3,  1],
       [ 0,  

In [540]:
meshgrid(range(10), range(10))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])]

In [24]:
seglen * srate

262144

In [927]:
class Args:
    def __init__(self, instruments):
        self.instruments = instruments
args = Args(["H1", "L1", "V1"])

In [928]:
from pycbc import detector
ifo1 = detector.Detector(args.instruments[0])
ifo2 = detector.Detector(args.instruments[1])
ifo3 = detector.Detector(args.instruments[2])
time_diff_12 = ifo1.light_travel_time_to_detector(ifo2)
time_diff_13 = ifo1.light_travel_time_to_detector(ifo3)

In [934]:
srate = 512
seglen = 512
N = seglen * srate
# N=int(2e2)
print(N)
t1 = 4+chisquare(4,N)
t2 = 4+chisquare(4,N)
t3 = 4+chisquare(4,N)
timing_error = 0.1
t2_coinc_window = int(ceil(time_diff_12 * (1+timing_error) * srate)) #int(83 / 2.)
t3_coinc_window = int(ceil(time_diff_13 * (1+timing_error) * srate)) #int(230 / 2.) -->26.4ms for 2-->3
sum((t1+t2+t3)>7**2) / len(t1), sum((t1+t2+t3)>7**2) / len(t1) * n_c

262144


(0.000225067138671875, 22242.228019714355)

In [935]:
t2_coinc_window, t3_coinc_window

(6, 16)

In [962]:
def number_tail(t2_coinc_window, t3_coinc_window):
    n_tail = (
        sum(
            (t2_coinc_window + 1 + arange(0, t2_coinc_window+1)) * (t3_coinc_window + 1 + arange(0, t2_coinc_window+1))
           ) + \
        sum(
            (2* t2_coinc_window + 1) * (t3_coinc_window + 1 + arange(t2_coinc_window+1, t3_coinc_window+1))
           )
    )
    return n_tail
def number_coincident_combinations(N, t2_coinc_window, t3_coinc_window):
    """Assumes t3_coinc_window>t2_coinc_window, and N is the number of time samples."""
    n_tail = number_tail(t2_coinc_window, t3_coinc_window)
    n_middle = (N - 2*(t3_coinc_window+1)) * (2 * t2_coinc_window + 1) * (2 * t3_coinc_window + 1) 
    n_c = 2 * n_tail + n_middle
    return n_c
number_coincident_combinations(N, t2_coinc_window, t3_coinc_window)

112455456

In [872]:
precalculated_idxs = get_indices_jit(2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window)

def get_i_j_k(coinc_idx, N, t2_coinc_window, t3_coinc_window, precalculated_idxs=None):
    """Get the indices i,j,k of the detector timeseries corresponding to coincident index coinc_idx. 
    Assumes t3_coinc_window>t2_coinc_window, and N is the number of time samples."""
    if coinc_idx < 0:
        raise ValueError("indices cannot be negative.")
    n_c = number_coincident_combinations(N, t2_coinc_window, t3_coinc_window)
    n_tail = number_tail(t2_coinc_window, t3_coinc_window)
    largest_window = max(t2_coinc_window, t3_coinc_window)
    if (coinc_idx > n_tail-1)&(coinc_idx < n_c-n_tail):
        i, remainder = divmod(coinc_idx - n_tail, (2*t2_coinc_window+1)*(2*t3_coinc_window+1))
        i += largest_window + 1
        j, remainder_2 = divmod(remainder, (2*t3_coinc_window+1))
        j += i - (t2_coinc_window)
        k = remainder_2 + i - (t3_coinc_window)
    else:
        if precalculated_idxs is None:
            precalculated_idxs = get_indices_jit(2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window)
        
        if not (coinc_idx > (n_tail-1)):
            # at the beginning
            i, j, k = precalculated_idxs[coinc_idx]
        else:
            # at the end
            i, j, k = precalculated_idxs[coinc_idx - (n_c+1)] + N - (2*t3_coinc_window + 2)
    return i, j, k

def three_det_sum_and_threshold(
    t1, t2, t3, t2_coinc_window, t3_coinc_window, threshold, precalculated_idxs=None
):
    temp = three_det_sum_jit(t1, t2, t3, t2_coinc_window, t3_coinc_window)
    mask = temp > threshold**2
    coinc_idx = nonzero(mask)[0]
    # later can improve the below loop by vectorizing the get_i_j_k function.
    det_idx = array([get_i_j_k(
        _i, N, t2_coinc_window, t3_coinc_window, precalculated_idxs=precalculated_idxs) 
            for _i in coinc_idx
    ])
    return sqrt(temp[mask]), det_idx

In [921]:
%time snrs, det_idx = three_det_sum_and_threshold( \
    t1, t2, t3, t2_coinc_window, t3_coinc_window, 7, precalculated_idxs=precalculated_idxs)

CPU times: user 1.58 s, sys: 567 ms, total: 2.14 s
Wall time: 2.14 s


In [879]:
snrs[]

array([7.13833436, 7.13559351, 7.26529356, ..., 7.27864822, 7.03596713,
       7.09449436])

In [888]:
i, j, k = det_idx[_ti]
sqrt(t1[i]+t2[j]+t3[k]), snrs[_ti]
print("Hallelujah")

Hallelujah


In [963]:
n_tail = number_tail(t2_coinc_window, t3_coinc_window)
n_c = number_coincident_combinations(N, t2_coinc_window, t3_coinc_window)

In [855]:
get_i_j_k(_it_, N, t2_coinc_window, t3_coinc_window, precalculated_idxs=precalculated_idxs), idx[_it_]

((0, 0, 1), array([0, 0, 1]))

In [618]:
divmod(5, 3)

(1, 2)

In [617]:
5%3

2

In [634]:
import tqdm

In [ ]:
tqdm.tqdm(range(n_tail, n_tail+4), "getting indices")

In [640]:
def get_indices_of_coincs(N, t2_coinc_window, t3_coinc_window):
    n_tail = number_tail(t2_coinc_window, t3_coinc_window)
    n_c = number_coincident_combinations(N, t2_coinc_window, t3_coinc_window)
    tt_idx = array([
        get_i_j_k(_i_, N, t2_coinc_window, t3_coinc_window) 
        for _i_ in tqdm.tqdm(range(n_tail, n_c-(n_tail)+1), "getting indices")
    ])
    return tt_idx

In [676]:
%time _ = get_indices_jit(2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window)

CPU times: user 2.93 ms, sys: 120 µs, total: 3.05 ms
Wall time: 3.23 ms


In [684]:
n_c

98824858

In [711]:
coinc_idx = n_c 
coinc_idx - (n_c+1)
precalculated_idxs[coinc_idx - (n_c+1)] + N - (2*t3_coinc_window + 2), idx[-(1)]

(array([262143, 262143, 262143]), array([262143, 262143, 262143]))

In [704]:
precalculated_idxs = get_indices_jit(2*(t3_coinc_window+1), t2_coinc_window, t3_coinc_window)

In [701]:
_[3000], idx[3000], _[-302] + N - (2*t3_coinc_window + 2), idx[-302]

(array([12, 11, 17]),
 array([12, 11, 17]),
 array([262141, 262139, 262143]),
 array([262141, 262139, 262143]))

In [677]:
len(_)/2, n_tail

(3940.0, 3940)

In [642]:
i_c = n_tail
while _i < i_c:

@njit
def get_indices_jit(N, t2_coinc_window, t3_coinc_window):
    idx = array([
        [i,j,k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return idx

3940

In [638]:
tt_idx

array([[15,  9,  1],
       [15,  9,  2],
       [15,  9,  3],
       [15,  9,  4]])

In [639]:
idx[n_tail:n_tail+4]

array([[15,  9,  1],
       [15,  9,  2],
       [15,  9,  3],
       [15,  9,  4]])

In [631]:
t_i = int(98824858 / 2)
get_i_j_k(t_i, N, t2_coinc_window, t3_coinc_window), idx[t_i]

((131072, 131066, 131058), array([131072, 131066, 131058]))

In [583]:
shape(idx)

(98824858, 3)

In [501]:
N

8192

In [116]:
shape(array(temp))

(3084954,)

In [1098]:
%time temp = three_det_sum_jit(t1, t2, t3, t2_coinc_window, t3_coinc_window)

CPU times: user 680 ms, sys: 690 ms, total: 1.37 s
Wall time: 1.36 s


In [1099]:
%time temp = three_det_sum(t1, t2, t3, t2_coinc_window, t3_coinc_window)

CPU times: user 1min 20s, sys: 2.55 s, total: 1min 23s
Wall time: 1min 23s


In [1097]:
%time temp = three_det_sum_idx_jit(t1, t2, t3, idx)

CPU times: user 280 ms, sys: 219 ms, total: 499 ms
Wall time: 496 ms


In [512]:
len(temp)

98824481

In [317]:
%time temp = three_det_sum_idx(t1, t2, t3, idx)

CPU times: user 5.45 s, sys: 38 ms, total: 5.49 s
Wall time: 5.5 s


In [1094]:
%time temp = three_det_sum_idx_array_jit(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 597 ms, sys: 1.04 s, total: 1.63 s
Wall time: 1.62 s


In [1090]:
%time temp = three_det_sum_idx_array_take_jit(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 794 ms, sys: 917 ms, total: 1.71 s
Wall time: 1.7 s


In [1091]:
%time temp = three_det_sum_idx_array_take(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 2.44 s, sys: 1.44 s, total: 3.88 s
Wall time: 3.88 s


In [1092]:
%time temp = three_det_sum_idx_array(t1, t2, t3, idx_1, idx_2, idx_3)

CPU times: user 698 ms, sys: 693 ms, total: 1.39 s
Wall time: 1.39 s


In [341]:
temp

array([32.47034313, 32.39089677, 30.06685365, ..., 46.27213832,
       38.42244677, 41.17865188])

In [160]:
%time idx = get_indices(len(t1), t2_coinc_window, t3_coinc_window)

CPU times: user 5.67 s, sys: 67.4 ms, total: 5.74 s
Wall time: 5.75 s


In [519]:
%time idx = get_indices_jit(len(t1), t2_coinc_window, t3_coinc_window)

CPU times: user 18.8 s, sys: 3.62 s, total: 22.4 s
Wall time: 22.7 s


Consider meshing.

In [ ]:
@njit
def get_indices_jit(N, t2_coinc_window, t3_coinc_window):
    idx = array([
        [i,j,k]
            for i in range(N)
                for j in range(max(i-t2_coinc_window, 0), min(N, i+t2_coinc_window+1))
                    for k in range(max(i-t3_coinc_window, 0), min(N, i+t3_coinc_window+1))
                ])
    return idx

In [110]:
sum(temp>7**2)

0.04275392524663054

In [111]:
degrees(pi/3)

59.99999999999999

In [ ]:
_t = temp

In [43]:
len(temp[80])

13

In [34]:
sum(array(temp) > 7**2)

/var/folders/2n/44xg31f92bd49rgkf9bsy4j80000gq/T/ipykernel_79644/4075904114.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  sum(array(temp) > 7**2)


TypeError: '>' not supported between instances of 'list' and 'int'