In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [5]:
from pycbc.events import hm_utils

In [151]:
analyze_lengths = [5120, 3000]
# analyze_lengths = [207377] #seg_len=512
t2_coinc_window = 8 #* 2
# t2_coinc_window = 8
t3_coinc_window = 17 #* 2
# t3_coinc_window = 17
t23_coinc_window = 17 #* 2
# t23_coinc_window = 17
alpha_23 = 1.3015216715223716
segment_overlap = 17

In [129]:
idx_combinations = {a_len: hm_utils.index_combinations(a_len, t2_coinc_window, 
    t3_coinc_window, np.int64) for a_len in np.unique(analyze_lengths)}

# for a_len, _idx_combinations in idx_combinations.items():
#     n2 = _idx_combinations[:,0] - _idx_combinations[:,1]
#     n3 = _idx_combinations[:,0] - _idx_combinations[:,2]
#     _cond = hm_utils.check_time_delay_is_physical(
#         n2, n3, t2_coinc_window, t3_coinc_window, alpha_23)
#     idx_combinations[a_len] = idx_combinations[a_len][_cond]
#     print("Removed {}/{} ({:.1f}%) unphysical combinations".format(
#                 len(_cond) - len(idx_combinations[a_len]), len(_cond), 
#                 100 * (len(_cond) - len(idx_combinations[a_len])) / len(_cond)))

### 3 detectors

Let $T_2=2 \times t_{2_{coinc}}+1$ where $t_{2_{coinc}}$ is t2_coinc_window. Then $T_2 T_3 \times max(T_2, T_3)$ steps in idx_combinations rows 2 and 3 guarantees IFO 2 and 3 have no coincidences with IFO 1. A further $T_2 T_3 \times T_{23}$ increments in row 3 ensures IFO 2 and IFO 3 have no coincidences, where $T_{23} = 2 \times t_{23} +1$ and $t_{23}$ represents the coincident window between IFOs 2 and 3. This requires a total of 
$$n_{incr} = T_2 T_3 \times (max(T_2, T_3) + T_{23})$$ increments in row 3 to guarantee no coincidences. Therefore, if we have $n_c=$len(idx_combinations) combinations, there will be
$$n_{slides}=\frac{n_c}{n_{incr}}$$
possible time slides.

In [161]:
T_2 = (2*t2_coinc_window+1)
T_3 = (2*t3_coinc_window+1)
T_23 = (2*t23_coinc_window+1)
n_incr = T_2 * T_3 * (max(T_2, T_3) + T_23)
n_c = len(idx_combinations[min(analyze_lengths)])
n_slides = n_c / float(n_incr)
n_slides

1.2227611044417768

In [137]:
T_2 * T_3 * max(T_2, T_3), n_incr

(157113, 314226)

In [130]:
t_2 = (t2_coinc_window+1)
t_3 = (t3_coinc_window+1)
t_23 = (t23_coinc_window+1)
n_incr = 4 * t_2 * t_3 * (max(t_2, t_3) + t_23)

In [131]:
4 * t_2 * t_3 * max(t_2, t_3), n_incr

(83300, 166600)

## Check this method works

Tomorrow:

    * I don't think this check is doing what i thought it was. Use identical pairs.

In [132]:
idx_combinations = idx_combinations[min(analyze_lengths)]
idx_combinations_on_source = idx_combinations.copy()

In [135]:
n_equal_indices = [1,1,1]
inc1, inc2 = 0, 0
# while n_equal_indices[2]>0 or n_equal_indices[1]>0:
for i in range(166):
    inc1 += 1000
    inc2 += 2000
    idx_combinations = idx_combinations_on_source.copy()
    idx_combinations[:,1] = np.roll(idx_combinations[:,1], inc1)#T_2 * T_3 * max(T_2, T_3))
    idx_combinations[:,2] = np.roll(idx_combinations[:,2], inc2)#n_incr)
    equal_indices = idx_combinations == idx_combinations_on_source
    n_equal_indices = equal_indices.sum(0)
    if n_equal_indices[2]==0 and n_equal_indices[1]==0:
        print(inc1, inc2)
    else:
        print(n_equal_indices)
#     equal_indices, n_equal_indices

[6780850    1136 5782004]
[6780850    8954 4909608]
[6780850    2404 4062132]
[6780850    4106 3237428]
[6780850    1954 2437372]
[6780850    3884 1660904]
[6780850    1370  909630]
[6780850    3414  180382]
[6780850    2152    2482]
[6780850    2574    1598]
[6780850 2383618    1972]
[6780850    2596    1868]
[6780850    3078    2358]
[6780850    2964    2266]
[6780850    2750    1856]
[6780850    1888    1790]
[6780850    1594    2448]
[6780850    1446    2102]
[6780850    1106    1402]
[6780850    1412    1416]
[6780850    2542     824]
[6780850    5150    1072]
[6780850    2866     812]
[6780850    2816    1064]
[6780850    1490    1378]
[6780850    2074    1284]
[6780850    1186    1348]
[6780850    1636    1324]
[6780850    1446    1392]
[6780850    1428    1062]
[6780850       0    1036]
[6780850     432    1168]
[6780850    3290     906]
[6780850    1826     946]
[6780850    1430    1050]
[6780850     812     814]
[6780850    2492     648]
[6780850     174     698]
[6780850    

In [96]:
n_equal_indices = [1,1,1]
inc1, inc2 = 0, 0
# while n_equal_indices[2]>0 or n_equal_indices[1]>0:
for i in range(22):
    inc1 += 1000
    inc2 += 2000
    idx_combinations = idx_combinations_on_source.copy()
    idx_combinations[:,1] = np.roll(idx_combinations[:,1], inc1)#T_2 * T_3 * max(T_2, T_3))
    idx_combinations[:,2] = np.roll(idx_combinations[:,2], inc2)#n_incr)
    equal_indices = idx_combinations == idx_combinations_on_source
    n_equal_indices = equal_indices.sum(0)
    if n_equal_indices[2]==0 and n_equal_indices[1]==0:
        print(inc1, inc2)
    else:
        print(n_equal_indices)
#     equal_indices, n_equal_indices

[1193500     524     164]
[1193500     410     356]
[1193500     124   88724]
[1193500     200   29518]
[1193500       0       2]
[1193500       0       4]
7000 14000
8000 16000
9000 18000
10000 20000
11000 22000
12000 24000
13000 26000
14000 28000
15000 30000
16000 32000
17000 34000
18000 36000
19000 38000
20000 40000
21000 42000
22000 44000


In [93]:
inc1, inc2

(7000, 14000)

### 2 detectors

In [166]:
idx_combinations = {a_len: hm_utils.index_combinations(a_len, t2_coinc_window, 
    None, np.int64) for a_len in np.unique(analyze_lengths)}
# idx_combinations[min(analyze_lengths)][1000:1100]
idx_combinations_on_source = idx_combinations[min(analyze_lengths)].copy()

In [159]:
len(idx_combinations[min(analyze_lengths)]), (2*t2_coinc_window+1) * min(analyze_lengths) 

(50928, 51000)

In [162]:
T_2**2

289

In [165]:
idx_combinations[]

{3000: array([[   0,    0],
        [   0,    1],
        [   0,    2],
        ...,
        [2999, 2997],
        [2999, 2998],
        [2999, 2999]]),
 5120: array([[   0,    0],
        [   0,    1],
        [   0,    2],
        ...,
        [5119, 5117],
        [5119, 5118],
        [5119, 5119]])}

In [184]:
shape(idx_combinations)[-1]

2

In [200]:
def max_number_timeslides(idx_onsource, t2_coinc_window, t3_coinc_window):
    nifo = shape(idx_onsource)[-1]
    T_2 = (2*t2_coinc_window+1)
    if nifo == 2:
        n_incr = T_2**2
    elif nifo == 3:
        T_3 = (2*t3_coinc_window+1)
        T_23 = (2*t23_coinc_window+1)
        n_incr = T_2 * T_3 * (max(T_2, T_3) + T_23)
    n_c = len(idx_onsource)
    n_slides = n_c / float(n_incr) - 1
    return int(n_slides)

def perform_timeslide(idx_onsource, slide_no, t2_coinc_window, t3_coinc_window):
    """Returns a copy of idx_combinations with the time indexes slid so they are no longer coincident"""
    idx = idx_onsource.copy()
    nifo = shape(idx)[-1]
    T_2 = (2*t2_coinc_window+1)
    if nifo == 2:
        n2_incr = T_2**2 * slide_no
        assert n2_incr < len(idx), "too many timeslides"
        idx[:,1] = np.roll(idx[:,1], n2_incr)
    elif nifo == 3:
        T_3 = (2*t3_coinc_window+1)
        T_23 = (2*t23_coinc_window+1)
        n2_incr = T_2 * T_3 * max(T_2, T_3) * slide_no
        n3_incr = T_2 * T_3 * (max(T_2, T_3) + T_23) * slide_no
        assert n2_incr < len(idx), "too many timeslides"
        idx[:,1] = np.roll(idx[:,1], n2_incr)
        idx[:,2] = np.roll(idx[:,2], n3_incr)
    return idx

    

In [201]:
max_number_timeslides(idx_combinations, t2_coinc_window, t3_coinc_window)

175

In [196]:
slide_idx(idx_combinations, 5, t2_coinc_window, t3_coinc_window)

array([[   0, 2902],
       [   0, 2903],
       [   0, 2888],
       ...,
       [2999, 2899],
       [2999, 2900],
       [2999, 2901]])

In [182]:
idx_combinations = idx_combinations_on_source.copy()
idx_combinations[:,1] = np.roll(idx_combinations[:,1], T_2**2)
equal_indices = idx_combinations == idx_combinations_on_source
n_equal_indices = equal_indices.sum(0)
n_equal_indices

array([50928,     0])

In [180]:
isin(idx_combinations_on_source[0], idx_combinations)

array([ True,  True])

In [178]:
idx_combinations, 

array([[   0, 2999],
       [   0,    0],
       [   0,    1],
       ...,
       [2999, 2996],
       [2999, 2997],
       [2999, 2998]])

In [177]:
equal_indices

array([[ True, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [ True, False],
       [ True, False]])